server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:loc}
  messages:
    basename: i18n/exception
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.polar.bear.api.models
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    call-setters-on-nulls: true

goods:
  image-storage-path: ${GOODS_IMAGE_STORAGE_PATH:./uploads/goods}
