CREATE TABLE IF NOT EXISTS admin_menu_info (
    MENU_NO BIGINT NOT NULL AUTO_INCREMENT,
    MENU_NAME VARCHAR(100) NOT NULL,
    ROUTE_NAME VARCHAR(100) NOT NULL,
    DISPLAY_ORDER INT NOT NULL,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    PRIMARY KEY (MENU_NO),
    UNIQUE KEY UK_ADMIN_MENU_ROUTE (ROUTE_NAME)
);

INSERT INTO admin_menu_info (MENU_NAME, ROUTE_NAME, DISPLAY_ORDER, USE_YN)
SELECT '대시보드', 'adminDashboard', 10, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM admin_menu_info WHERE ROUTE_NAME = 'adminDashboard');
INSERT INTO admin_menu_info (MENU_NAME, ROUTE_NAME, DISPLAY_ORDER, USE_YN)
SELECT '상품 관리', 'adminGoodsList', 20, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM admin_menu_info WHERE ROUTE_NAME = 'adminGoodsList');
INSERT INTO admin_menu_info (MENU_NAME, ROUTE_NAME, DISPLAY_ORDER, USE_YN)
SELECT '이벤트 관리', 'adminEventList', 30, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM admin_menu_info WHERE ROUTE_NAME = 'adminEventList');
INSERT INTO admin_menu_info (MENU_NAME, ROUTE_NAME, DISPLAY_ORDER, USE_YN)
SELECT '회원 관리', 'adminUserList', 40, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM admin_menu_info WHERE ROUTE_NAME = 'adminUserList');
INSERT INTO admin_menu_info (MENU_NAME, ROUTE_NAME, DISPLAY_ORDER, USE_YN)
SELECT '관리자 관리', 'adminAdminList', 50, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM admin_menu_info WHERE ROUTE_NAME = 'adminAdminList');
INSERT INTO admin_menu_info (MENU_NAME, ROUTE_NAME, DISPLAY_ORDER, USE_YN)
SELECT '문의 관리', 'adminQnaList', 60, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM admin_menu_info WHERE ROUTE_NAME = 'adminQnaList');
