CREATE TABLE IF NOT EXISTS event_info (
    EVENT_NO BIGINT NOT NULL AUTO_INCREMENT,
    EVENT_TITLE VARCHAR(200) NOT NULL,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    DISPLAY_YN CHAR(1) NOT NULL DEFAULT 'Y',
    EVENT_START_DATE DATETIME NOT NULL,
    EVENT_END_DATE DATETIME NOT NULL,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(100) NOT NULL,
    UPDT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDT_ID VARCHAR(100) NOT NULL,
    PRIMARY KEY (EVENT_NO)
);

CREATE TABLE IF NOT EXISTS event_goods (
    EVENT_GOODS_NO BIGINT NOT NULL AUTO_INCREMENT,
    EVENT_NO BIGINT NOT NULL,
    GOODS_NO BIGINT NOT NULL,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(100) NOT NULL,
    UPDT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDT_ID VARCHAR(100) NOT NULL,
    PRIMARY KEY (EVENT_GOODS_NO),
    UNIQUE KEY UK_EVENT_GOODS (EVENT_NO, GOODS_NO),
    CONSTRAINT FK_EVENT_GOODS_EVENT FOREIGN KEY (EVENT_NO) REFERENCES event_info (EVENT_NO),
    CONSTRAINT FK_EVENT_GOODS_GOODS FOREIGN KEY (GOODS_NO) REFERENCES goods_info (GOODS_NO)
);

CREATE TABLE IF NOT EXISTS event_image (
    EVENT_IMAGE_NO BIGINT NOT NULL AUTO_INCREMENT,
    EVENT_NO BIGINT NOT NULL,
    MAIN_IMAGE_YN CHAR(1) NOT NULL DEFAULT 'N',
    IMAGE_URL VARCHAR(1000) NOT NULL,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(100) NOT NULL,
    UPDT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDT_ID VARCHAR(100) NOT NULL,
    PRIMARY KEY (EVENT_IMAGE_NO),
    CONSTRAINT FK_EVENT_IMAGE_EVENT FOREIGN KEY (EVENT_NO) REFERENCES event_info (EVENT_NO)
);
