-- MySQL 8 migration for an existing product_info/product_image schema.
-- Existing BRAND_NAME values are migrated to BRAND_NAME_KO because the legacy schema
-- does not distinguish Korean and English names. Existing categories become depth 1 roots.

RENAME TABLE product_info TO goods_info, product_image TO goods_image;

ALTER TABLE goods_image DROP FOREIGN KEY FK_PRODUCT_IMAGE_PRODUCT_NO;

CREATE TABLE brand_info (
    BRAND_NO BIGINT NOT NULL AUTO_INCREMENT,
    BRAND_NAME_KO VARCHAR(100) NOT NULL,
    BRAND_NAME_EN VARCHAR(100) NULL,
    BRAND_COUNTRY VARCHAR(100) NULL,
    BRAND_LOGO_IMAGE_URL VARCHAR(1000) NULL,
    DISPLAY_YN CHAR(1) NOT NULL DEFAULT 'Y',
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    UPDT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDT_ID VARCHAR(30) NOT NULL,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(30) NOT NULL,
    PRIMARY KEY (BRAND_NO),
    UNIQUE KEY UK_BRAND_INFO_NAME_KO (BRAND_NAME_KO)
);

CREATE TABLE category_info (
    CATEGORY_NO BIGINT NOT NULL AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    CATEGORY_DEPTH INT NOT NULL DEFAULT 1,
    PARENT_CATEGORY_NO BIGINT NULL,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    DISPLAY_YN CHAR(1) NOT NULL DEFAULT 'Y',
    UPDT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDT_ID VARCHAR(30) NOT NULL,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    REG_ID VARCHAR(30) NOT NULL,
    PRIMARY KEY (CATEGORY_NO),
    KEY IX_CATEGORY_INFO_PARENT_NO (PARENT_CATEGORY_NO),
    CONSTRAINT FK_CATEGORY_INFO_PARENT_NO FOREIGN KEY (PARENT_CATEGORY_NO) REFERENCES category_info (CATEGORY_NO)
);

INSERT INTO brand_info (BRAND_NAME_KO, DISPLAY_YN, USE_YN, UPDT_DATE, UPDT_ID, REG_DATE, REG_ID)
SELECT BRAND_NAME, 'Y', 'Y', MIN(UPDT_DATE), MIN(UPDT_ID), MIN(REG_DATE), MIN(REG_ID)
FROM goods_info
WHERE BRAND_NAME IS NOT NULL AND BRAND_NAME != ''
GROUP BY BRAND_NAME;

INSERT INTO category_info (CATEGORY_NAME, CATEGORY_DEPTH, PARENT_CATEGORY_NO, USE_YN, DISPLAY_YN,
    UPDT_DATE, UPDT_ID, REG_DATE, REG_ID)
SELECT CATEGORY_NAME, 1, NULL, 'Y', 'Y', MIN(UPDT_DATE), MIN(UPDT_ID), MIN(REG_DATE), MIN(REG_ID)
FROM goods_info
GROUP BY CATEGORY_NAME;

ALTER TABLE goods_info
    ADD COLUMN BRAND_NO BIGINT NULL AFTER PRODUCT_NAME_EN,
    ADD COLUMN CATEGORY_NO BIGINT NULL AFTER BRAND_NO;

UPDATE goods_info G
LEFT JOIN brand_info B ON B.BRAND_NAME_KO = G.BRAND_NAME
INNER JOIN category_info C ON C.CATEGORY_NAME = G.CATEGORY_NAME
SET G.BRAND_NO = B.BRAND_NO,
    G.CATEGORY_NO = C.CATEGORY_NO;

ALTER TABLE goods_info
    MODIFY COLUMN CATEGORY_NO BIGINT NOT NULL,
    DROP COLUMN BRAND_NAME,
    DROP COLUMN CATEGORY_NAME,
    RENAME COLUMN PRODUCT_NO TO GOODS_NO,
    RENAME COLUMN PRODUCT_CODE TO GOODS_CODE,
    RENAME COLUMN PRODUCT_NAME_KO TO GOODS_NAME_KO,
    RENAME COLUMN PRODUCT_NAME_EN TO GOODS_NAME_EN,
    RENAME COLUMN PRODUCT_STATUS TO GOODS_STATUS,
    DROP INDEX UK_PRODUCT_INFO_CODE,
    ADD UNIQUE KEY UK_GOODS_INFO_CODE (GOODS_CODE),
    ADD KEY IX_GOODS_INFO_BRAND_NO (BRAND_NO),
    ADD KEY IX_GOODS_INFO_CATEGORY_NO (CATEGORY_NO),
    ADD CONSTRAINT FK_GOODS_INFO_BRAND_NO FOREIGN KEY (BRAND_NO) REFERENCES brand_info (BRAND_NO),
    ADD CONSTRAINT FK_GOODS_INFO_CATEGORY_NO FOREIGN KEY (CATEGORY_NO) REFERENCES category_info (CATEGORY_NO);

ALTER TABLE goods_image
    RENAME COLUMN PRODUCT_IMAGE_NO TO GOODS_IMAGE_NO,
    RENAME COLUMN PRODUCT_NO TO GOODS_NO,
    DROP INDEX IX_PRODUCT_IMAGE_PRODUCT_NO,
    ADD KEY IX_GOODS_IMAGE_GOODS_NO (GOODS_NO),
    ADD CONSTRAINT FK_GOODS_IMAGE_GOODS_NO FOREIGN KEY (GOODS_NO) REFERENCES goods_info (GOODS_NO);

UPDATE goods_image
SET IMAGE_URL = CONCAT('/goods-images/', SUBSTRING(IMAGE_URL, CHAR_LENGTH('/product-images/') + 1))
WHERE IMAGE_URL LIKE '/product-images/%';
